name: 'dev_build'
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: '发布版本'
        required: true
        type: string
      is_prerelease:
        description: '是预发布的?'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # branch: ['master', '1.19', '1.19.1', '1.19.2','1.19.4']
        branch: ['master']       
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Read value from Properties-file
        uses: madhead/read-java-properties@latest
        id: properties
        with:
          file: gradle.properties
          all: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Make gradlew executable - ${{ matrix.branch }}
        run: chmod +x ./gradlew
      - name: Build artifacts - ${{ matrix.branch }}
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'success')
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        id: download
        with:
          path: build/results
      - name: Remove *-dev.jar
        run: |
          rm /home/runner/work/Wurst7/Wurst7/build/results/Package/*-dev.jar || true   
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: '${{ inputs.release_version }}'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: ${{ inputs.is_prerelease }}
          title: ${{ inputs.release_version }}
          files: ${{steps.download.outputs.download-path}}
